- id: ty
  name: Ty Type Checker
  entry: ty check
  language: system
  types: [python]


- id: pytest
  name: Run Pytest
  entry: pytest
  language: system
  pass_filenames: false
  types: [python]
  always_run: true
  stages: [commit]